# Generated by Django 5.1.2 on 2024-10-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=256, verbose_name='School Name')),
                ('district', models.CharField(max_length=256, verbose_name='District')),
                ('school_address', models.CharField(max_length=256, verbose_name='Address')),
                ('advisor_name', models.CharField(max_length=256, verbose_name='Advisor Name')),
                ('advisor_email', models.CharField(max_length=256, verbose_name='Advisor Email')),
                ('advisor_phone_number', models.CharField(max_length=256, verbose_name='Advisor Phone Number')),
                ('advisor_emergency_contact', models.CharField(max_length=256, verbose_name='Emergency Contact')),
                ('advisor_emergency_contact_phone', models.CharField(max_length=256, verbose_name='Emergency Contact Phone Number')),
            ],
        ),
    ]
