# Generated by Django 5.1.2 on 2024-10-29 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaf_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='school',
        ),
        migrations.RemoveField(
            model_name='team',
            name='students',
        ),
        migrations.AddField(
            model_name='team',
            name='advisor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='omaf_app.advisor'),
            preserve_default=False,
        ),
    ]
