# Generated by Django 5.1.2 on 2024-10-29 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaf_app', '0002_alter_school_school_name_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='advisor_email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='advisor_emergency_contact',
        ),
        migrations.RemoveField(
            model_name='school',
            name='advisor_emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='advisor_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='advisor_phone_number',
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_name', models.CharField(max_length=256, verbose_name='Advisor Name')),
                ('advisor_email', models.CharField(max_length=256, verbose_name='Advisor Email')),
                ('advisor_phone_number', models.CharField(max_length=256, verbose_name='Advisor Phone Number')),
                ('advisor_emergency_contact', models.CharField(max_length=256, verbose_name='Emergency Contact')),
                ('advisor_emergency_contact_phone', models.CharField(max_length=256, verbose_name='Emergency Contact Phone Number')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omaf_app.school')),
            ],
        ),
    ]
