# Generated by Django 5.1.2 on 2024-10-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaf_app', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='t_shirt',
            field=models.CharField(blank=True, max_length=32, verbose_name='T-Shirt size'),
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(blank=True, default=57, on_delete=django.db.models.deletion.CASCADE, to='omaf_app.team'),
            preserve_default=False,
        ),
    ]
