# Generated by Django 5.1.2 on 2024-10-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaf_app', '0004_student_t_shirt_student_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='t_shirt',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra X Large'), ('NA', 'No T-shirt')], max_length=32, verbose_name='T-Shirt size'),
        ),
    ]
